#:schema https://raw.githubusercontent.com/godmothersfire/asphalt/refs/heads/main/schema.json

[creator]
type = "group"
id = 12787072

[codegen]
typescript = false
style = "nested"
strip_extensions = true
content = false

[inputs.core]
path = "assets/core/**/*"
output_path = "workspace/core/assets"
output_basename = "init"

[inputs.title]
path = "assets/title/**/*"
output_path = "workplace/title/assets"
output_basename = "init"

[inputs.universe]
path = "assets/universe/**/*"
output_path = "workspace/universe/assets"
output_basename = "init"
