# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
lute = "luau-lang/lute@1.0.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.68.0"
StyLua = "JohnnyMorganz/StyLua@2.5.2"
selene = "Kampfkarren/selene@0.31.0"
pesde = "pesde-pkg/pesde@0.7.3+registry.0.2.3"
rojo = "rojo-rbx/rojo@7.7.0-rc.1"
blink = "1Axen/blink@0.18.8"
lune = "lune-org/lune@0.10.4"
