local path = require("@std/path")

-- Rojo

export type RojoMappings = { [string]: { RojoMappingSegment } }

export type RojoMappingSegment = {
	name: string,
	className: string?,
}

export type RojoPath = string | { optional: string }

export type RojoNode = {
	["$className"]: string?,
	["$path"]: RojoPath?,
	[string]: RojoNode,
}

export type RojoProjectTarget = "source" | "output"

-- Rojo Sourcemap

export type SourcemapNode = {
	name: string,
	filePaths: { string }?,
	children: { SourcemapNode }?,
}

export type Sourcemap = { [string]: string }

-- Monorepo

export type Place = {
	title: string,
	subtitle: string?,
	folderName: string,
	placeId: string?,
	dependencies: { string }?,
}

export type PlaceMixin = {
	transpile: boolean,
	folderName: string,
	rojo: {
		{
			name: string,
			className: string?,
		}
	},
}

export type LuauConfig = {
	wth: {
		place: Place?,
		placeMixin: PlaceMixin?,
	},
}

export type MonorepoMember = {
	place: Place?,
	placeMixin: PlaceMixin?,

	folderName: string,
	dirName: string,
	dirPath: path.Pathlike,
	configPath: path.Pathlike,
	outputDirPath: path.Pathlike,

	rojoMappings: {
		[RojoProjectTarget]: { [keyof<RojoMappings>]: path.Pathlike? },
	},
}

export type Monorepo = { [any]: MonorepoMember }

export type RepositoryConfig = typeof(require("@libs/../../.config"))

-- Build

export type BuildCacheFile = {
	lastModified: number,
	hash: string,
	size: number,
}

export type BuildCache = { [string]: BuildCacheFile }

export type BuildState = {
	repository: RepositoryConfig,

	member: MonorepoMember,
	place: Place,
	dependencies: { MonorepoMember },

	cache: BuildCache,
	sourcemap: Sourcemap,
}

return nil
